name: lampa_server
description: Lampa Self-Hosted Server with SQLite
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  dart_frog_web_socket: ^1.0.3
  drift: ^2.15.0
  http: any
  path: ^1.8.3
  sqlite3: ^2.3.0
  televerse: ^1.22.0
  uuid: ^4.2.1

dev_dependencies:
  build_runner: ^2.4.8
  dart_frog_lint: ^0.1.0
  drift_dev: ^2.15.0
  mocktail: ^1.0.3
  test: ^1.25.5

